-- 0021: Pass 2 — photos for the 45 holdouts. Sources: Wikipedia (EN/EL),
-- Wikimedia Commons, Pexels (broader queries). Duplicate URLs that would
-- end up under multiple cities have been removed (left as placeholder).
-- Re-runnable.

DELETE FROM photos WHERE id LIKE 'photo_pass2_%';

INSERT INTO photos (id, city_id, subject_type, source, url, attribution_text, attribution_url, license, is_primary, sort_order) VALUES
  ('photo_pass2_vouliagmeni', 'city_seed20_vouliagmeni', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Vouliagmenis_lake_2.JPG/1920px-Vouliagmenis_lake_2.JPG',
   'C messier', 'https://commons.wikimedia.org/wiki/File%3AVouliagmenis%20lake%202.JPG',
   'CC0', 1, 0),
  ('photo_pass2_poros', 'city_seed20_poros', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/0/0e/Poros_aerial_viw.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Poros',
   'Wikimedia', 1, 0),
  ('photo_pass2_korinthos', 'city_seed20_korinthos', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Cirith_Ungol_-_2022216160529_2022-08-04_Wacken_-_Sven_-_5DS_R_-_0294_-_5DSR7381.jpg/3840px-Cirith_Ungol_-_2022216160529_2022-08-04_Wacken_-_Sven_-_5DS_R_-_0294_-_5DSR7381.jpg',
   'Wikipedia', 'https://el.wikipedia.org/wiki/Cirith_Ungol',
   'Wikimedia', 1, 0),
  ('photo_pass2_kalamata', 'city_seed20_kalamata', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/c/c4/Kalamata%2C_Peloponnese%2C_Greece.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Kalamata',
   'Wikimedia', 1, 0),
  ('photo_pass2_sparta', 'city_seed20_sparta', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/d/db/Spartan_Territory_Before_371_BC.png',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Sparta',
   'Wikimedia', 1, 0),
  ('photo_pass2_pylos', 'city_seed20_pylos', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/14467986/pexels-photo-14467986.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Klaidi Gkini / Pexels', 'https://www.pexels.com/photo/14467986/',
   'Pexels', 1, 0),
  ('photo_pass2_gythio', 'city_seed20_gythio', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Gythio_Port%2C_Greece_-_Diliff.jpg/3840px-Gythio_Port%2C_Greece_-_Diliff.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Gytheio',
   'Wikimedia', 1, 0),
  ('photo_pass2_tripoli', 'city_seed20_tripoli', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Theodoros_Kolokotronis_Stadium.jpg/1920px-Theodoros_Kolokotronis_Stadium.jpg',
   'Apostolos Papageorgiou', 'https://commons.wikimedia.org/wiki/File%3ATheodoros%20Kolokotronis%20Stadium.jpg',
   'CC BY-SA 3.0', 1, 0),
  ('photo_pass2_areopoli', 'city_seed20_areopoli', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/32900250/pexels-photo-32900250.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Lydia Griva / Pexels', 'https://www.pexels.com/photo/32900250/',
   'Pexels', 1, 0),
  ('photo_pass2_mystras', 'city_seed20_mystras', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/%CE%9C%CF%85%CF%83%CF%84%CF%81%CE%AC%CF%82%2C_Mystras.jpg/3840px-%CE%9C%CF%85%CF%83%CF%84%CF%81%CE%AC%CF%82%2C_Mystras.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Mystras',
   'Wikimedia', 1, 0),
  ('photo_pass2_arachova', 'city_seed20_arachova', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/28724529/pexels-photo-28724529.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Greece-China  News / Pexels', 'https://www.pexels.com/photo/28724529/',
   'Pexels', 1, 0),
  ('photo_pass2_galaxidi', 'city_seed20_galaxidi', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/365668/pexels-photo-365668.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Daniela Elena Tentis / Pexels', 'https://www.pexels.com/photo/365668/',
   'Pexels', 1, 0),
  ('photo_pass2_karpenisi', 'city_seed20_karpenisi', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/31553753/pexels-photo-31553753.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Angelos Lamprakopoulos / Pexels', 'https://www.pexels.com/photo/31553753/',
   'Pexels', 1, 0),
  ('photo_pass2_karystos', 'city_seed20_karystos', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/27126979/pexels-photo-27126979.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Alex Ravvas / Pexels', 'https://www.pexels.com/photo/27126979/',
   'Pexels', 1, 0),
  ('photo_pass2_lamia', 'city_seed20_lamia', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/1/11/Lamia_Montage_L.png',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Lamia_(city)',
   'Wikimedia', 1, 0),
  ('photo_pass2_larissa', 'city_seed20_larissa', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/12077054/pexels-photo-12077054.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Hugo Sykes / Pexels', 'https://www.pexels.com/photo/12077054/',
   'Pexels', 1, 0),
  ('photo_pass2_portaria', 'city_seed20_portaria', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/5333377/pexels-photo-5333377.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Chavdar Lungov / Pexels', 'https://www.pexels.com/photo/5333377/',
   'Pexels', 1, 0),
  ('photo_pass2_alonissos', 'city_seed20_alonissos', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/f/f4/Alonissos2.JPG',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Alonnisos',
   'Wikimedia', 1, 0),
  ('photo_pass2_skyros', 'city_seed20_skyros', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Skyros-chora.JPG/1920px-Skyros-chora.JPG',
   'Han borg', 'https://commons.wikimedia.org/wiki/File%3ASkyros-chora.JPG',
   'Public domain', 1, 0),
  ('photo_pass2_preveza', 'city_seed20_preveza', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/6/6d/Port_of_Preveza_2013.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Preveza',
   'Wikimedia', 1, 0),
  ('photo_pass2_sivota', 'city_seed20_sivota', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/10199329/pexels-photo-10199329.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Mike Anast / Pexels', 'https://www.pexels.com/photo/10199329/',
   'Pexels', 1, 0),
  ('photo_pass2_arta', 'city_seed20_arta', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/17861495/pexels-photo-17861495.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Emirhan Emiroğlu / Pexels', 'https://www.pexels.com/photo/17861495/',
   'Pexels', 1, 0),
  ('photo_pass2_zagori', 'city_seed20_zagori', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/9963323/pexels-photo-9963323.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Daniel Liberman / Pexels', 'https://www.pexels.com/photo/9963323/',
   'Pexels', 1, 0),
  ('photo_pass2_igoumenitsa', 'city_seed20_igoumenitsa', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/11478663/pexels-photo-11478663.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Arti Kh / Pexels', 'https://www.pexels.com/photo/11478663/',
   'Pexels', 1, 0),
  ('photo_pass2_veria', 'city_seed20_veria', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/20303298/pexels-photo-20303298.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Mr Alex Photography / Pexels', 'https://www.pexels.com/photo/20303298/',
   'Pexels', 1, 0),
  ('photo_pass2_naoussa_imathia', 'city_seed20_naoussa_imathia', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Naoussa._The_Macedonian_Struggle_Museum_in_Naoussa%2C_Macedonia%2C_Greece.jpg/1920px-Naoussa._The_Macedonian_Struggle_Museum_in_Naoussa%2C_Macedonia%2C_Greece.jpg',
   'Lappeion', 'https://commons.wikimedia.org/wiki/File%3ANaoussa.%20The%20Macedonian%20Struggle%20Museum%20in%20Naoussa%2C%20Macedonia%2C%20Greece.jpg',
   'CC BY-SA 4.0', 1, 0),
  ('photo_pass2_serres', 'city_seed20_serres', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/30410208/pexels-photo-30410208.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Lydia Griva / Pexels', 'https://www.pexels.com/photo/30410208/',
   'Pexels', 1, 0),
  ('photo_pass2_kilkis', 'city_seed20_kilkis', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/26764302/pexels-photo-26764302.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Efrem C. / Pexels', 'https://www.pexels.com/photo/26764302/',
   'Pexels', 1, 0),
  ('photo_pass2_pella', 'city_seed20_pella', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/7/78/Pella_House_atrium.jpg',
   'Brian Donovan', 'https://commons.wikimedia.org/wiki/File%3APella%20House%20atrium.jpg',
   'Public domain', 1, 0),
  ('photo_pass2_grevena', 'city_seed20_grevena', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/723029/pexels-photo-723029.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'GEORGE DESIPRIS / Pexels', 'https://www.pexels.com/photo/723029/',
   'Pexels', 1, 0),
  ('photo_pass2_xanthi', 'city_seed20_xanthi', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/15277734/pexels-photo-15277734.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Joanna Asimenos / Pexels', 'https://www.pexels.com/photo/15277734/',
   'Pexels', 1, 0),
  ('photo_pass2_alexandroupolis', 'city_seed20_alexandroupolis', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/8/82/%CE%A6%CE%AC%CF%81%CE%BF%CF%82_%CE%91%CE%BB%CE%B5%CE%BE%CE%B1%CE%BD%CE%B4%CF%81%CE%BF%CF%8D%CF%80%CE%BF%CE%BB%CE%B7%CF%82_2.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Alexandroupolis',
   'Wikimedia', 1, 0),
  ('photo_pass2_kea', 'city_seed20_kea', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/32168367/pexels-photo-32168367.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Daciana  Cristina  Visan / Pexels', 'https://www.pexels.com/photo/32168367/',
   'Pexels', 1, 0),
  ('photo_pass2_sikinos', 'city_seed20_sikinos', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/4684017/pexels-photo-4684017.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Mary Fotinaki / Pexels', 'https://www.pexels.com/photo/4684017/',
   'Pexels', 1, 0),
  ('photo_pass2_nisyros', 'city_seed20_nisyros', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/5949018/pexels-photo-5949018.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Tom D''Arby / Pexels', 'https://www.pexels.com/photo/5949018/',
   'Pexels', 1, 0),
  ('photo_pass2_tilos', 'city_seed20_tilos', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/30711199/pexels-photo-30711199.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'George Alex / Pexels', 'https://www.pexels.com/photo/30711199/',
   'Pexels', 1, 0),
  ('photo_pass2_lipsi', 'city_seed20_lipsi', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/%CE%9B%CE%B5%CE%B9%CF%88%CE%BF%CE%AF_%CE%A0%CE%B1%CE%BD%CE%BF%CF%81%CE%B1%CE%BC%CE%B9%CE%BA%CE%AC.jpg/1920px-%CE%9B%CE%B5%CE%B9%CF%88%CE%BF%CE%AF_%CE%A0%CE%B1%CE%BD%CE%BF%CF%81%CE%B1%CE%BC%CE%B9%CE%BA%CE%AC.jpg',
   'Sarantis Karydas', 'https://commons.wikimedia.org/wiki/File%3A%CE%9B%CE%B5%CE%B9%CF%88%CE%BF%CE%AF%20%CE%A0%CE%B1%CE%BD%CE%BF%CF%81%CE%B1%CE%BC%CE%B9%CE%BA%CE%AC.jpg',
   'CC BY-SA 4.0', 1, 0),
  ('photo_pass2_limnos', 'city_seed20_limnos', 'location', 'licensed_stock',
   'https://upload.wikimedia.org/wikipedia/commons/6/6d/MirinaLimnosGreece.jpg',
   'Wikipedia', 'https://en.wikipedia.org/wiki/Lemnos',
   'Wikimedia', 1, 0),
  ('photo_pass2_fournoi', 'city_seed20_fournoi', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/34746215/pexels-photo-34746215.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'DIMITRI XENOS / Pexels', 'https://www.pexels.com/photo/34746215/',
   'Pexels', 1, 0),
  ('photo_pass2_sitia', 'city_seed20_sitia', 'location', 'licensed_stock',
   'https://images.pexels.com/photos/6273914/pexels-photo-6273914.jpeg?auto=compress&cs=tinysrgb&w=1800',
   'Chris K / Pexels', 'https://www.pexels.com/photo/6273914/',
   'Pexels', 1, 0);
